// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: opentelemetry/proto/profiles/v1experimental/profiles.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenTelemetry.Proto.Profiles.V1Experimental {

  /// <summary>Holder for reflection information generated from opentelemetry/proto/profiles/v1experimental/profiles.proto</summary>
  public static partial class ProfilesReflection {

    #region Descriptor
    /// <summary>File descriptor for opentelemetry/proto/profiles/v1experimental/profiles.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfilesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjpvcGVudGVsZW1ldHJ5L3Byb3RvL3Byb2ZpbGVzL3YxZXhwZXJpbWVudGFs",
            "L3Byb2ZpbGVzLnByb3RvEitvcGVudGVsZW1ldHJ5LnByb3RvLnByb2ZpbGVz",
            "LnYxZXhwZXJpbWVudGFsGipvcGVudGVsZW1ldHJ5L3Byb3RvL2NvbW1vbi92",
            "MS9jb21tb24ucHJvdG8aLm9wZW50ZWxlbWV0cnkvcHJvdG8vcmVzb3VyY2Uv",
            "djEvcmVzb3VyY2UucHJvdG8aP29wZW50ZWxlbWV0cnkvcHJvdG8vcHJvZmls",
            "ZXMvdjFleHBlcmltZW50YWwvcHByb2ZleHRlbmRlZC5wcm90byJoCgxQcm9m",
            "aWxlc0RhdGESWAoRcmVzb3VyY2VfcHJvZmlsZXMYASADKAsyPS5vcGVudGVs",
            "ZW1ldHJ5LnByb3RvLnByb2ZpbGVzLnYxZXhwZXJpbWVudGFsLlJlc291cmNl",
            "UHJvZmlsZXMivwEKEFJlc291cmNlUHJvZmlsZXMSOwoIcmVzb3VyY2UYASAB",
            "KAsyKS5vcGVudGVsZW1ldHJ5LnByb3RvLnJlc291cmNlLnYxLlJlc291cmNl",
            "ElIKDnNjb3BlX3Byb2ZpbGVzGAIgAygLMjoub3BlbnRlbGVtZXRyeS5wcm90",
            "by5wcm9maWxlcy52MWV4cGVyaW1lbnRhbC5TY29wZVByb2ZpbGVzEhIKCnNj",
            "aGVtYV91cmwYAyABKAlKBgjoBxDpByK4AQoNU2NvcGVQcm9maWxlcxJCCgVz",
            "Y29wZRgBIAEoCzIzLm9wZW50ZWxlbWV0cnkucHJvdG8uY29tbW9uLnYxLklu",
            "c3RydW1lbnRhdGlvblNjb3BlEk8KCHByb2ZpbGVzGAIgAygLMj0ub3BlbnRl",
            "bGVtZXRyeS5wcm90by5wcm9maWxlcy52MWV4cGVyaW1lbnRhbC5Qcm9maWxl",
            "Q29udGFpbmVyEhIKCnNjaGVtYV91cmwYAyABKAkiwQIKEFByb2ZpbGVDb250",
            "YWluZXISEgoKcHJvZmlsZV9pZBgBIAEoDBIcChRzdGFydF90aW1lX3VuaXhf",
            "bmFubxgCIAEoBhIaChJlbmRfdGltZV91bml4X25hbm8YAyABKAYSOwoKYXR0",
            "cmlidXRlcxgEIAMoCzInLm9wZW50ZWxlbWV0cnkucHJvdG8uY29tbW9uLnYx",
            "LktleVZhbHVlEiAKGGRyb3BwZWRfYXR0cmlidXRlc19jb3VudBgFIAEoDRIf",
            "ChdvcmlnaW5hbF9wYXlsb2FkX2Zvcm1hdBgGIAEoCRIYChBvcmlnaW5hbF9w",
            "YXlsb2FkGAcgASgMEkUKB3Byb2ZpbGUYCCABKAsyNC5vcGVudGVsZW1ldHJ5",
            "LnByb3RvLnByb2ZpbGVzLnYxZXhwZXJpbWVudGFsLlByb2ZpbGVCpwEKLmlv",
            "Lm9wZW50ZWxlbWV0cnkucHJvdG8ucHJvZmlsZXMudjFleHBlcmltZW50YWxC",
            "DVByb2ZpbGVzUHJvdG9QAVo2Z28ub3BlbnRlbGVtZXRyeS5pby9wcm90by9v",
            "dGxwL3Byb2ZpbGVzL3YxZXhwZXJpbWVudGFsqgIrT3BlblRlbGVtZXRyeS5Q",
            "cm90by5Qcm9maWxlcy5WMUV4cGVyaW1lbnRhbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OpenTelemetry.Proto.Common.V1.CommonReflection.Descriptor, global::OpenTelemetry.Proto.Resource.V1.ResourceReflection.Descriptor, global::OpenTelemetry.Proto.Profiles.V1Experimental.PprofextendedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfilesData), global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfilesData.Parser, new[]{ "ResourceProfiles" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles), global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles.Parser, new[]{ "Resource", "ScopeProfiles", "SchemaUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles), global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles.Parser, new[]{ "Scope", "Profiles", "SchemaUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer), global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer.Parser, new[]{ "ProfileId", "StartTimeUnixNano", "EndTimeUnixNano", "Attributes", "DroppedAttributesCount", "OriginalPayloadFormat", "OriginalPayload", "Profile" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// ProfilesData represents the profiles data that can be stored in persistent storage,
  /// OR can be embedded by other protocols that transfer OTLP profiles data but do not
  /// implement the OTLP protocol.
  ///
  /// The main difference between this message and collector protocol is that
  /// in this message there will not be any "control" or "metadata" specific to
  /// OTLP protocol.
  ///
  /// When new fields are added into this message, the OTLP request MUST be updated
  /// as well.
  /// </summary>
  public sealed partial class ProfilesData : pb::IMessage<ProfilesData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProfilesData> _parser = new pb::MessageParser<ProfilesData>(() => new ProfilesData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProfilesData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfilesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfilesData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfilesData(ProfilesData other) : this() {
      resourceProfiles_ = other.resourceProfiles_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfilesData Clone() {
      return new ProfilesData(this);
    }

    /// <summary>Field number for the "resource_profiles" field.</summary>
    public const int ResourceProfilesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles> _repeated_resourceProfiles_codec
        = pb::FieldCodec.ForMessage(10, global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles.Parser);
    private readonly pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles> resourceProfiles_ = new pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles>();
    /// <summary>
    /// An array of ResourceProfiles.
    /// For data coming from a single resource this array will typically contain
    /// one element. Intermediary nodes that receive data from multiple origins
    /// typically batch the data before forwarding further and in that case this
    /// array will contain multiple elements.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ResourceProfiles> ResourceProfiles {
      get { return resourceProfiles_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProfilesData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProfilesData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!resourceProfiles_.Equals(other.resourceProfiles_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= resourceProfiles_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      resourceProfiles_.WriteTo(output, _repeated_resourceProfiles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      resourceProfiles_.WriteTo(ref output, _repeated_resourceProfiles_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += resourceProfiles_.CalculateSize(_repeated_resourceProfiles_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProfilesData other) {
      if (other == null) {
        return;
      }
      resourceProfiles_.Add(other.resourceProfiles_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            resourceProfiles_.AddEntriesFrom(input, _repeated_resourceProfiles_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            resourceProfiles_.AddEntriesFrom(ref input, _repeated_resourceProfiles_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A collection of ScopeProfiles from a Resource.
  /// </summary>
  public sealed partial class ResourceProfiles : pb::IMessage<ResourceProfiles>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceProfiles> _parser = new pb::MessageParser<ResourceProfiles>(() => new ResourceProfiles());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceProfiles> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfilesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceProfiles() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceProfiles(ResourceProfiles other) : this() {
      resource_ = other.resource_ != null ? other.resource_.Clone() : null;
      scopeProfiles_ = other.scopeProfiles_.Clone();
      schemaUrl_ = other.schemaUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceProfiles Clone() {
      return new ResourceProfiles(this);
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 1;
    private global::OpenTelemetry.Proto.Resource.V1.Resource resource_;
    /// <summary>
    /// The resource for the profiles in this message.
    /// If this field is not set then no resource info is known.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenTelemetry.Proto.Resource.V1.Resource Resource {
      get { return resource_; }
      set {
        resource_ = value;
      }
    }

    /// <summary>Field number for the "scope_profiles" field.</summary>
    public const int ScopeProfilesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles> _repeated_scopeProfiles_codec
        = pb::FieldCodec.ForMessage(18, global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles.Parser);
    private readonly pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles> scopeProfiles_ = new pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles>();
    /// <summary>
    /// A list of ScopeProfiles that originate from a resource.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ScopeProfiles> ScopeProfiles {
      get { return scopeProfiles_; }
    }

    /// <summary>Field number for the "schema_url" field.</summary>
    public const int SchemaUrlFieldNumber = 3;
    private string schemaUrl_ = "";
    /// <summary>
    /// The Schema URL, if known. This is the identifier of the Schema that the resource data
    /// is recorded in. To learn more about Schema URL see
    /// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
    /// This schema_url applies to the data in the "resource" field. It does not apply
    /// to the data in the "scope_profiles" field which have their own schema_url field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SchemaUrl {
      get { return schemaUrl_; }
      set {
        schemaUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceProfiles);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceProfiles other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Resource, other.Resource)) return false;
      if(!scopeProfiles_.Equals(other.scopeProfiles_)) return false;
      if (SchemaUrl != other.SchemaUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resource_ != null) hash ^= Resource.GetHashCode();
      hash ^= scopeProfiles_.GetHashCode();
      if (SchemaUrl.Length != 0) hash ^= SchemaUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resource_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resource);
      }
      scopeProfiles_.WriteTo(output, _repeated_scopeProfiles_codec);
      if (SchemaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SchemaUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resource_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resource);
      }
      scopeProfiles_.WriteTo(ref output, _repeated_scopeProfiles_codec);
      if (SchemaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SchemaUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resource);
      }
      size += scopeProfiles_.CalculateSize(_repeated_scopeProfiles_codec);
      if (SchemaUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SchemaUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceProfiles other) {
      if (other == null) {
        return;
      }
      if (other.resource_ != null) {
        if (resource_ == null) {
          Resource = new global::OpenTelemetry.Proto.Resource.V1.Resource();
        }
        Resource.MergeFrom(other.Resource);
      }
      scopeProfiles_.Add(other.scopeProfiles_);
      if (other.SchemaUrl.Length != 0) {
        SchemaUrl = other.SchemaUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resource_ == null) {
              Resource = new global::OpenTelemetry.Proto.Resource.V1.Resource();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 18: {
            scopeProfiles_.AddEntriesFrom(input, _repeated_scopeProfiles_codec);
            break;
          }
          case 26: {
            SchemaUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resource_ == null) {
              Resource = new global::OpenTelemetry.Proto.Resource.V1.Resource();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 18: {
            scopeProfiles_.AddEntriesFrom(ref input, _repeated_scopeProfiles_codec);
            break;
          }
          case 26: {
            SchemaUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A collection of ProfileContainers produced by an InstrumentationScope.
  /// </summary>
  public sealed partial class ScopeProfiles : pb::IMessage<ScopeProfiles>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ScopeProfiles> _parser = new pb::MessageParser<ScopeProfiles>(() => new ScopeProfiles());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ScopeProfiles> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfilesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScopeProfiles() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScopeProfiles(ScopeProfiles other) : this() {
      scope_ = other.scope_ != null ? other.scope_.Clone() : null;
      profiles_ = other.profiles_.Clone();
      schemaUrl_ = other.schemaUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScopeProfiles Clone() {
      return new ScopeProfiles(this);
    }

    /// <summary>Field number for the "scope" field.</summary>
    public const int ScopeFieldNumber = 1;
    private global::OpenTelemetry.Proto.Common.V1.InstrumentationScope scope_;
    /// <summary>
    /// The instrumentation scope information for the profiles in this message.
    /// Semantically when InstrumentationScope isn't set, it is equivalent with
    /// an empty instrumentation scope name (unknown).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenTelemetry.Proto.Common.V1.InstrumentationScope Scope {
      get { return scope_; }
      set {
        scope_ = value;
      }
    }

    /// <summary>Field number for the "profiles" field.</summary>
    public const int ProfilesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer> _repeated_profiles_codec
        = pb::FieldCodec.ForMessage(18, global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer.Parser);
    private readonly pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer> profiles_ = new pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer>();
    /// <summary>
    /// A list of ProfileContainers that originate from an instrumentation scope.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfileContainer> Profiles {
      get { return profiles_; }
    }

    /// <summary>Field number for the "schema_url" field.</summary>
    public const int SchemaUrlFieldNumber = 3;
    private string schemaUrl_ = "";
    /// <summary>
    /// The Schema URL, if known. This is the identifier of the Schema that the metric data
    /// is recorded in. To learn more about Schema URL see
    /// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
    /// This schema_url applies to all profiles in the "profiles" field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SchemaUrl {
      get { return schemaUrl_; }
      set {
        schemaUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ScopeProfiles);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ScopeProfiles other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Scope, other.Scope)) return false;
      if(!profiles_.Equals(other.profiles_)) return false;
      if (SchemaUrl != other.SchemaUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (scope_ != null) hash ^= Scope.GetHashCode();
      hash ^= profiles_.GetHashCode();
      if (SchemaUrl.Length != 0) hash ^= SchemaUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (scope_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Scope);
      }
      profiles_.WriteTo(output, _repeated_profiles_codec);
      if (SchemaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SchemaUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (scope_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Scope);
      }
      profiles_.WriteTo(ref output, _repeated_profiles_codec);
      if (SchemaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SchemaUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (scope_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Scope);
      }
      size += profiles_.CalculateSize(_repeated_profiles_codec);
      if (SchemaUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SchemaUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ScopeProfiles other) {
      if (other == null) {
        return;
      }
      if (other.scope_ != null) {
        if (scope_ == null) {
          Scope = new global::OpenTelemetry.Proto.Common.V1.InstrumentationScope();
        }
        Scope.MergeFrom(other.Scope);
      }
      profiles_.Add(other.profiles_);
      if (other.SchemaUrl.Length != 0) {
        SchemaUrl = other.SchemaUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (scope_ == null) {
              Scope = new global::OpenTelemetry.Proto.Common.V1.InstrumentationScope();
            }
            input.ReadMessage(Scope);
            break;
          }
          case 18: {
            profiles_.AddEntriesFrom(input, _repeated_profiles_codec);
            break;
          }
          case 26: {
            SchemaUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (scope_ == null) {
              Scope = new global::OpenTelemetry.Proto.Common.V1.InstrumentationScope();
            }
            input.ReadMessage(Scope);
            break;
          }
          case 18: {
            profiles_.AddEntriesFrom(ref input, _repeated_profiles_codec);
            break;
          }
          case 26: {
            SchemaUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A ProfileContainer represents a single profile. It wraps pprof profile with OpenTelemetry specific metadata.
  /// </summary>
  public sealed partial class ProfileContainer : pb::IMessage<ProfileContainer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProfileContainer> _parser = new pb::MessageParser<ProfileContainer>(() => new ProfileContainer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProfileContainer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenTelemetry.Proto.Profiles.V1Experimental.ProfilesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfileContainer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfileContainer(ProfileContainer other) : this() {
      profileId_ = other.profileId_;
      startTimeUnixNano_ = other.startTimeUnixNano_;
      endTimeUnixNano_ = other.endTimeUnixNano_;
      attributes_ = other.attributes_.Clone();
      droppedAttributesCount_ = other.droppedAttributesCount_;
      originalPayloadFormat_ = other.originalPayloadFormat_;
      originalPayload_ = other.originalPayload_;
      profile_ = other.profile_ != null ? other.profile_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfileContainer Clone() {
      return new ProfileContainer(this);
    }

    /// <summary>Field number for the "profile_id" field.</summary>
    public const int ProfileIdFieldNumber = 1;
    private pb::ByteString profileId_ = pb::ByteString.Empty;
    /// <summary>
    /// A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
    /// all zeroes is considered invalid.
    ///
    /// This field is required.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ProfileId {
      get { return profileId_; }
      set {
        profileId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_time_unix_nano" field.</summary>
    public const int StartTimeUnixNanoFieldNumber = 2;
    private ulong startTimeUnixNano_;
    /// <summary>
    /// start_time_unix_nano is the start time of the profile.
    /// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
    ///
    /// This field is semantically required and it is expected that end_time >= start_time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong StartTimeUnixNano {
      get { return startTimeUnixNano_; }
      set {
        startTimeUnixNano_ = value;
      }
    }

    /// <summary>Field number for the "end_time_unix_nano" field.</summary>
    public const int EndTimeUnixNanoFieldNumber = 3;
    private ulong endTimeUnixNano_;
    /// <summary>
    /// end_time_unix_nano is the end time of the profile.
    /// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
    ///
    /// This field is semantically required and it is expected that end_time >= start_time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EndTimeUnixNano {
      get { return endTimeUnixNano_; }
      set {
        endTimeUnixNano_ = value;
      }
    }

    /// <summary>Field number for the "attributes" field.</summary>
    public const int AttributesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::OpenTelemetry.Proto.Common.V1.KeyValue> _repeated_attributes_codec
        = pb::FieldCodec.ForMessage(34, global::OpenTelemetry.Proto.Common.V1.KeyValue.Parser);
    private readonly pbc::RepeatedField<global::OpenTelemetry.Proto.Common.V1.KeyValue> attributes_ = new pbc::RepeatedField<global::OpenTelemetry.Proto.Common.V1.KeyValue>();
    /// <summary>
    /// attributes is a collection of key/value pairs. Note, global attributes
    /// like server name can be set using the resource API. Examples of attributes:
    ///
    ///     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
    ///     "/http/server_latency": 300
    ///     "abc.com/myattribute": true
    ///     "abc.com/score": 10.239
    ///
    /// The OpenTelemetry API specification further restricts the allowed value types:
    /// https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
    /// Attribute keys MUST be unique (it is not allowed to have more than one
    /// attribute with the same key).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes {
      get { return attributes_; }
    }

    /// <summary>Field number for the "dropped_attributes_count" field.</summary>
    public const int DroppedAttributesCountFieldNumber = 5;
    private uint droppedAttributesCount_;
    /// <summary>
    /// dropped_attributes_count is the number of attributes that were discarded. Attributes
    /// can be discarded because their keys are too long or because there are too many
    /// attributes. If this value is 0, then no attributes were dropped.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DroppedAttributesCount {
      get { return droppedAttributesCount_; }
      set {
        droppedAttributesCount_ = value;
      }
    }

    /// <summary>Field number for the "original_payload_format" field.</summary>
    public const int OriginalPayloadFormatFieldNumber = 6;
    private string originalPayloadFormat_ = "";
    /// <summary>
    /// Specifies format of the original payload. Common values are defined in semantic conventions. [required if original_payload is present]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginalPayloadFormat {
      get { return originalPayloadFormat_; }
      set {
        originalPayloadFormat_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "original_payload" field.</summary>
    public const int OriginalPayloadFieldNumber = 7;
    private pb::ByteString originalPayload_ = pb::ByteString.Empty;
    /// <summary>
    /// Original payload can be stored in this field. This can be useful for users who want to get the original payload.
    /// Formats such as JFR are highly extensible and can contain more information than what is defined in this spec.
    /// Inclusion of original payload should be configurable by the user. Default behavior should be to not include the original payload.
    /// If the original payload is in pprof format, it SHOULD not be included in this field.
    /// The field is optional, however if it is present `profile` MUST be present and contain the same profiling information.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString OriginalPayload {
      get { return originalPayload_; }
      set {
        originalPayload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "profile" field.</summary>
    public const int ProfileFieldNumber = 8;
    private global::OpenTelemetry.Proto.Profiles.V1Experimental.Profile profile_;
    /// <summary>
    /// This is a reference to a pprof profile. Required, even when original_payload is present.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenTelemetry.Proto.Profiles.V1Experimental.Profile Profile {
      get { return profile_; }
      set {
        profile_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProfileContainer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProfileContainer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProfileId != other.ProfileId) return false;
      if (StartTimeUnixNano != other.StartTimeUnixNano) return false;
      if (EndTimeUnixNano != other.EndTimeUnixNano) return false;
      if(!attributes_.Equals(other.attributes_)) return false;
      if (DroppedAttributesCount != other.DroppedAttributesCount) return false;
      if (OriginalPayloadFormat != other.OriginalPayloadFormat) return false;
      if (OriginalPayload != other.OriginalPayload) return false;
      if (!object.Equals(Profile, other.Profile)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProfileId.Length != 0) hash ^= ProfileId.GetHashCode();
      if (StartTimeUnixNano != 0UL) hash ^= StartTimeUnixNano.GetHashCode();
      if (EndTimeUnixNano != 0UL) hash ^= EndTimeUnixNano.GetHashCode();
      hash ^= attributes_.GetHashCode();
      if (DroppedAttributesCount != 0) hash ^= DroppedAttributesCount.GetHashCode();
      if (OriginalPayloadFormat.Length != 0) hash ^= OriginalPayloadFormat.GetHashCode();
      if (OriginalPayload.Length != 0) hash ^= OriginalPayload.GetHashCode();
      if (profile_ != null) hash ^= Profile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProfileId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ProfileId);
      }
      if (StartTimeUnixNano != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(StartTimeUnixNano);
      }
      if (EndTimeUnixNano != 0UL) {
        output.WriteRawTag(25);
        output.WriteFixed64(EndTimeUnixNano);
      }
      attributes_.WriteTo(output, _repeated_attributes_codec);
      if (DroppedAttributesCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(DroppedAttributesCount);
      }
      if (OriginalPayloadFormat.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(OriginalPayloadFormat);
      }
      if (OriginalPayload.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(OriginalPayload);
      }
      if (profile_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Profile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProfileId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ProfileId);
      }
      if (StartTimeUnixNano != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(StartTimeUnixNano);
      }
      if (EndTimeUnixNano != 0UL) {
        output.WriteRawTag(25);
        output.WriteFixed64(EndTimeUnixNano);
      }
      attributes_.WriteTo(ref output, _repeated_attributes_codec);
      if (DroppedAttributesCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(DroppedAttributesCount);
      }
      if (OriginalPayloadFormat.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(OriginalPayloadFormat);
      }
      if (OriginalPayload.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(OriginalPayload);
      }
      if (profile_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Profile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProfileId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProfileId);
      }
      if (StartTimeUnixNano != 0UL) {
        size += 1 + 8;
      }
      if (EndTimeUnixNano != 0UL) {
        size += 1 + 8;
      }
      size += attributes_.CalculateSize(_repeated_attributes_codec);
      if (DroppedAttributesCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DroppedAttributesCount);
      }
      if (OriginalPayloadFormat.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginalPayloadFormat);
      }
      if (OriginalPayload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OriginalPayload);
      }
      if (profile_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Profile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProfileContainer other) {
      if (other == null) {
        return;
      }
      if (other.ProfileId.Length != 0) {
        ProfileId = other.ProfileId;
      }
      if (other.StartTimeUnixNano != 0UL) {
        StartTimeUnixNano = other.StartTimeUnixNano;
      }
      if (other.EndTimeUnixNano != 0UL) {
        EndTimeUnixNano = other.EndTimeUnixNano;
      }
      attributes_.Add(other.attributes_);
      if (other.DroppedAttributesCount != 0) {
        DroppedAttributesCount = other.DroppedAttributesCount;
      }
      if (other.OriginalPayloadFormat.Length != 0) {
        OriginalPayloadFormat = other.OriginalPayloadFormat;
      }
      if (other.OriginalPayload.Length != 0) {
        OriginalPayload = other.OriginalPayload;
      }
      if (other.profile_ != null) {
        if (profile_ == null) {
          Profile = new global::OpenTelemetry.Proto.Profiles.V1Experimental.Profile();
        }
        Profile.MergeFrom(other.Profile);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ProfileId = input.ReadBytes();
            break;
          }
          case 17: {
            StartTimeUnixNano = input.ReadFixed64();
            break;
          }
          case 25: {
            EndTimeUnixNano = input.ReadFixed64();
            break;
          }
          case 34: {
            attributes_.AddEntriesFrom(input, _repeated_attributes_codec);
            break;
          }
          case 40: {
            DroppedAttributesCount = input.ReadUInt32();
            break;
          }
          case 50: {
            OriginalPayloadFormat = input.ReadString();
            break;
          }
          case 58: {
            OriginalPayload = input.ReadBytes();
            break;
          }
          case 66: {
            if (profile_ == null) {
              Profile = new global::OpenTelemetry.Proto.Profiles.V1Experimental.Profile();
            }
            input.ReadMessage(Profile);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ProfileId = input.ReadBytes();
            break;
          }
          case 17: {
            StartTimeUnixNano = input.ReadFixed64();
            break;
          }
          case 25: {
            EndTimeUnixNano = input.ReadFixed64();
            break;
          }
          case 34: {
            attributes_.AddEntriesFrom(ref input, _repeated_attributes_codec);
            break;
          }
          case 40: {
            DroppedAttributesCount = input.ReadUInt32();
            break;
          }
          case 50: {
            OriginalPayloadFormat = input.ReadString();
            break;
          }
          case 58: {
            OriginalPayload = input.ReadBytes();
            break;
          }
          case 66: {
            if (profile_ == null) {
              Profile = new global::OpenTelemetry.Proto.Profiles.V1Experimental.Profile();
            }
            input.ReadMessage(Profile);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
